stock_list = [
  {'stock_ticker': 'AAPL', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'MSFT', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'AMZN', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'GOOG', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'GOOGL', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'FB', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'BABA', 'exchange': 'NYSE'},
  {'stock_ticker': 'TSLA', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'BRK-A', 'exchange': 'NYSE'},
  {'stock_ticker': 'BRK-B', 'exchange': 'NYSE'},
  {'stock_ticker': 'TSM', 'exchange': 'NYSE'},
  {'stock_ticker': 'V', 'exchange': 'NYSE'},
  {'stock_ticker': 'WMT', 'exchange': 'NYSE'},
  {'stock_ticker': 'JNJ', 'exchange': 'NYSE'},
  {'stock_ticker': 'JPM', 'exchange': 'NYSE'},
  {'stock_ticker': 'MA', 'exchange': 'NYSE'},
  {'stock_ticker': 'PG', 'exchange': 'NYSE'},
  {'stock_ticker': 'UNH', 'exchange': 'NYSE'},
  {'stock_ticker': 'NVDA', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'DIS', 'exchange': 'NYSE'},
  {'stock_ticker': 'HD', 'exchange': 'NYSE'},
  {'stock_ticker': 'BAC', 'exchange': 'NYSE'},
  {'stock_ticker': 'VZ', 'exchange': 'NYSE'},
  {'stock_ticker': 'PYPL', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'CMCSA', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'INTC', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'KO', 'exchange': 'NYSE'},
  {'stock_ticker': 'PFE', 'exchange': 'NYSE'},
  {'stock_ticker': 'NFLX', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'T', 'exchange': 'NYSE'},
  {'stock_ticker': 'ADBE', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'PDD', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'NKE', 'exchange': 'NYSE'},
  {'stock_ticker': 'MPNGY', 'exchange': 'NYSEMKT'},
  {'stock_ticker': 'MPNGY', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'TM', 'exchange': 'NYSE'},
  {'stock_ticker': 'MRK', 'exchange': 'NYSE'},
  {'stock_ticker': 'NVS', 'exchange': 'NYSE'},
  {'stock_ticker': 'CRM', 'exchange': 'NYSE'},
  {'stock_ticker': 'XOM', 'exchange': 'NYSE'},
  {'stock_ticker': 'ABT', 'exchange': 'NYSE'},
  {'stock_ticker': 'CSCO', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'ASML', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'ABBV', 'exchange': 'NYSE'},
  {'stock_ticker': 'TMO', 'exchange': 'NYSE'},
  {'stock_ticker': 'PEP', 'exchange': 'NASDAQ'},
  {'stock_ticker': 'ORCL', 'exchange': 'NYSE'},
  {'stock_ticker': 'CVX', 'exchange': 'NYSE'},
  {'stock_ticker': 'PROSY', 'exchange': 'NYSEMKT'},
  {'stock_ticker': 'QCOM', 'exchange': 'NASDAQ'},
]

stock_list_2 = [
	{ 'ticker_symbol': 'AAPL', 'company_name': 'Apple Inc', 'market_index': 'NASDAQ', 'industry': 'Consumer Electronics' },
	{ 'ticker_symbol': 'MSFT', 'company_name': 'Microsoft Corporation', 'market_index': 'NASDAQ', 'industry': 'Internet Services & Infrastructure' },
	{ 'ticker_symbol': 'AMZN', 'company_name': 'Amazon.com Inc.', 'market_index': 'NASDAQ', 'industry': 'Specialty Retail' },
	{ 'ticker_symbol': 'GOOG', 'company_name': 'Alphabet Inc', 'market_index': 'NASDAQ', 'industry': 'Internet Services & Infrastructure' },
	{ 'ticker_symbol': 'GOOGL', 'company_name': 'Alphabet Inc', 'market_index': 'NASDAQ', 'industry': 'Internet Services & Infrastructure	' },
	{ 'ticker_symbol': 'FB', 'company_name': 'Facebook Inc', 'market_index': 'NASDAQ', 'industry': 'Internet Services & Infrastructure' },
	{ 'ticker_symbol': 'BABA', 'company_name': 'Alibaba Group Holding Ltd', 'market_index': 'NYSE', 'industry': 'Specialty Retail' },
	{ 'ticker_symbol': 'TSLA', 'company_name': 'Tesla Inc', 'market_index': 'NASDAQ', 'industry': 'Automobile Manufacturers' },
	{ 'ticker_symbol': 'BRK-A', 'company_name': 'Berkshire Hathaway Inc.', 'market_index': 'NYSE', 'industry': 'Multi-line Insurance' },
	{ 'ticker_symbol': 'BRK-B', 'company_name': 'Berkshire Hathaway Inc.', 'market_index': 'NYSE', 'industry': 'Multi-line Insurance' },
	{ 'ticker_symbol': 'TSM', 'company_name': 'Taiwan Semiconductor Manufacturing', 'market_index': 'NYSE', 'industry': 'Semiconductors' },
	{ 'ticker_symbol': 'V', 'company_name': 'Visa Inc', 'market_index': 'NYSE', 'industry': 'Consumer Finance' },
	{ 'ticker_symbol': 'WMT', 'company_name': 'Walmart Inc', 'market_index': 'NYSE', 'industry': 'Hypermarkets & Super Centers	' },
	{ 'ticker_symbol': 'JNJ', 'company_name': 'Johnson & Johnson', 'market_index': 'NYSE', 'industry': 'Pharmaceuticals	' },
	{ 'ticker_symbol': 'JPM', 'company_name': 'JPMorgan Chase & Co.', 'market_index': 'NYSE', 'industry': 'Diversified Banks	' },
	{ 'ticker_symbol': 'MA', 'company_name': 'Mastercard Incorporated', 'market_index': 'NYSE', 'industry': 'Consumer Finance' },
	{ 'ticker_symbol': 'PG', 'company_name': 'Procter & Gamble Co.', 'market_index': 'NYSE', 'industry': 'Household & Personal Products' },
	{ 'ticker_symbol': 'UNH', 'company_name': 'Unitedhealth Group Inc', 'market_index': 'NYSE', 'industry': 'Managed Health Care	' },
	{ 'ticker_symbol': 'NVDA', 'company_name': 'NVIDIA Corp', 'market_index': 'NASDAQ', 'industry': 'Semiconductors' },
	{ 'ticker_symbol': 'DIS', 'company_name': 'Walt Disney Co (The)', 'market_index': 'NYSE', 'industry': 'Media' },
	{ 'ticker_symbol': 'HD', 'company_name': 'Home Depot, Inc.', 'market_index': 'NYSE', 'industry': 'Home Improvement Retail' },
	{ 'ticker_symbol': 'BAC', 'company_name': 'Bank Of America Corp.', 'market_index': 'NYSE', 'industry': 'Diversified Banks	' },
	{ 'ticker_symbol': 'VZ', 'company_name': 'Verizon Communications Inc', 'market_index': 'NYSE', 'industry': 'Telecommunication Services' },
	{ 'ticker_symbol': 'PYPL', 'company_name': 'PayPal Holdings Inc', 'market_index': 'NASDAQ', 'industry': 'Consumer Finance' },
	{ 'ticker_symbol': 'CMCSA', 'company_name': 'Comcast Corp', 'market_index': 'NASDAQ', 'industry': 'Cable & Satellite	' },
	{ 'ticker_symbol': 'INTC', 'company_name': 'Intel Corp.', 'market_index': 'NASDAQ', 'industry': 'Semiconductors' },
	{ 'ticker_symbol': 'KO', 'company_name': 'Coca-Cola Co', 'market_index': 'NYSE', 'industry': 'Soft Drinks	' },
	{ 'ticker_symbol': 'PFE', 'company_name': 'Pfizer Inc.', 'market_index': 'NYSE', 'industry': 'Pharmaceuticals	' },
	{ 'ticker_symbol': 'NFLX', 'company_name': 'NetFlix Inc', 'market_index': 'NASDAQ', 'industry': 'Media' },
	{ 'ticker_symbol': 'T', 'company_name': 'AT&T, Inc.', 'market_index': 'NYSE', 'industry': 'Telecommunication Services' },
	{ 'ticker_symbol': 'ADBE', 'company_name': 'Adobe Inc', 'market_index': 'NASDAQ', 'industry': 'Application Software' },
	{ 'ticker_symbol': 'PDD', 'company_name': 'Pinduoduo Inc', 'market_index': 'NASDAQ', 'industry': 'Specialty ' },
	{ 'ticker_symbol': 'NKE', 'company_name': 'Nike, Inc.', 'market_index': 'NYSE', 'industry': 'Footwear' },
	{ 'ticker_symbol': 'MPNGY', 'company_name': 'Meituan Dianping', 'market_index': 'NYSEMKT', 'industry': 'Internet Retail' },
	{ 'ticker_symbol': 'MPNGY', 'company_name': 'Meituan Dianping', 'market_index': 'NASDAQ', 'industry': 'Internet Retail' },
	{ 'ticker_symbol': 'TM', 'company_name': 'Toyota Motor Corporation', 'market_index': 'NYSE', 'industry': 'Automobile Manufacturers' },
	{ 'ticker_symbol': 'MRK', 'company_name': 'Merck & Co Inc', 'market_index': 'NYSE', 'industry': 'Pharmaceuticals' },
	{ 'ticker_symbol': 'NVS', 'company_name': 'Novartis AG', 'market_index': 'NYSE', 'industry': 'Pharmaceuticals' },
	{ 'ticker_symbol': 'CRM', 'company_name': 'Salesforce.Com Inc', 'market_index': 'NYSE', 'industry': 'Application Software' },
	{ 'ticker_symbol': 'XOM', 'company_name': 'Exxon Mobil Corp.', 'market_index': 'NYSE', 'industry': 'Integrated Oil & Gas' },
	{ 'ticker_symbol': 'ABT', 'company_name': 'Abbott Laboratories', 'market_index': 'NYSE', 'industry': 'Health Care Equipment' },
	{ 'ticker_symbol': 'CSCO', 'company_name': 'Cisco Systems, Inc.', 'market_index': 'NASDAQ', 'industry': 'Communications Equipment	' },
	{ 'ticker_symbol': 'ASML', 'company_name': 'ASML Holding NV', 'market_index': 'NASDAQ', 'industry': 'Semiconductor Equipment' },
	{ 'ticker_symbol': 'ABBV', 'company_name': 'Abbvie Inc', 'market_index': 'NYSE', 'industry': 'Pharmaceuticals' },
	{ 'ticker_symbol': 'TMO', 'company_name': 'Thermo Fisher Scientific Inc.', 'market_index': 'NYSE', 'industry': 'Life Sciences Tools' },
	{ 'ticker_symbol': 'PEP', 'company_name': 'Pepsico Inc.', 'market_index': 'NASDAQ', 'industry': 'Soft Drinks	' },
	{ 'ticker_symbol': 'ORCL', 'company_name': 'Oracle Corp.', 'market_index': 'NYSE', 'industry': 'Internet Services & Infrastructure	' },
	{ 'ticker_symbol': 'CVX', 'company_name': 'Chevron Corp.', 'market_index': 'NYSE', 'industry': 'Integrated Oil & ' },
	{ 'ticker_symbol': 'PROSY', 'company_name': 'Prosus N.V.', 'market_index': 'NYSEMKT', 'industry': 'Internet Content & Information	' },
	{ 'ticker_symbol': 'QCOM', 'company_name': 'Qualcomm, Inc.', 'market_index': 'NASDAQ', 'industry': 'Semiconductors' }